services:
  uzchess-backend:
    build: .
    command: >
      sh -c "npm run migrate && node dist/main.js"
    env_file:
      - .env
    ports:
      - "8008:8008"
    restart: always
    container_name: uzchess
    networks:
      - uzchess
    volumes:
      - uploads:/app/uploads/

  db:
    image: postgres:18-alpine
    env_file:
      - .env
    container_name: postgres-db
    networks:
      - uzchess
    volumes:
      - uzchess:/var/lib/postgresql/data

volumes:
  uzchess:
  uploads:

networks:
  uzchess:
    driver: bridge
